//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAyarlar
    {
        public int id { get; set; }
        public string logourl { get; set; }
        public string baslik { get; set; }
        public string footer { get; set; }
        public string modul1 { get; set; }
        public string modul2 { get; set; }
        public string modul3 { get; set; }
        public string title { get; set; }
        public string hakkimda { get; set; }
    }
}
