//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int id { get; set; }
        public Nullable<int> yonetici { get; set; }
        public string detay { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tblYonetici tblYonetici { get; set; }
    }
}
