//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarkalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMarkalar()
        {
            this.tblStokYonetimi = new HashSet<tblStokYonetimi>();
            this.tblUrunler = new HashSet<tblUrunler>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string resimUrl { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<int> cesit { get; set; }
    
        public virtual tblCesitler tblCesitler { get; set; }
        public virtual tblKategoriler tblKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokYonetimi> tblStokYonetimi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrunler> tblUrunler { get; set; }
    }
}
