//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStokYonetimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStokYonetimi()
        {
            this.tblUrunler1 = new HashSet<tblUrunler>();
        }
    
        public int id { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<int> cesit { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> marka { get; set; }
        public string durum { get; set; }
    
        public virtual tblCesitler tblCesitler { get; set; }
        public virtual tblKategoriler tblKategoriler { get; set; }
        public virtual tblMarkalar tblMarkalar { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUrunler> tblUrunler1 { get; set; }
    }
}
