//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiparisKaydi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSiparisKaydi()
        {
            this.tblMusteriler = new HashSet<tblMusteriler>();
        }
    
        public int id { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string onay { get; set; }
        public Nullable<int> musteri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMusteriler> tblMusteriler { get; set; }
        public virtual tblMusteriler tblMusteriler1 { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
