//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrunler()
        {
            this.tblSiparisKaydi = new HashSet<tblSiparisKaydi>();
            this.tblStokYonetimi = new HashSet<tblStokYonetimi>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string aciklama { get; set; }
        public string resimUrl { get; set; }
        public string resimUrl2 { get; set; }
        public string resimUrl3 { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string beden { get; set; }
        public string olcu { get; set; }
        public string renk { get; set; }
        public string indirim { get; set; }
        public string oylama { get; set; }
        public string iade { get; set; }
        public string teslimat { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<int> stok { get; set; }
        public Nullable<int> marka { get; set; }
        public Nullable<int> cesit { get; set; }
    
        public virtual tblCesitler tblCesitler { get; set; }
        public virtual tblKategoriler tblKategoriler { get; set; }
        public virtual tblMarkalar tblMarkalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSiparisKaydi> tblSiparisKaydi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStokYonetimi> tblStokYonetimi { get; set; }
        public virtual tblStokYonetimi tblStokYonetimi1 { get; set; }
    }
}
